{{ if .Values.acs.central_cluster }}
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  central:
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          size: 100Gi
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    telemetry:
      enabled: true
  egress:
    connectivityPolicy: Online
  monitoring:
    openshift:
      enabled: true
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Enabled
{{ end }}
