---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers[0]/resources/limits/cpu
        value: 4  ## Default is 8
    target:
      kind: Deployment
      name: central-db

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers[0]/resources/limits/memory
        value: 16  ## Default is 16Gi
    target:
      kind: Deployment
      name: central-db