kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: automation-hub-file-storage
  namespace: ansible-automation-platform
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi

