clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management
    - hello-world
    - external-secrets-operator
    - ansible-automation-platform
    - postgresql ## Postgres for keycloak
    - rhbk-sso   ## Keycloak operator -- forms operator group
    - stackrox      
    - rhacs-operator 

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.8

    rhacs:
       name: rhacs-operator
       channel: stable

    rhbk:
       name: rhbk-operator
       namespace: rhbk-sso
       channel: stable-v22

    # ossm-elasticsearch:
    #    name: elasticseach-operator
    #    channel: stable
    
    # ossm-jaeger:
    #    name: jaeger-operator
    #    channel: stable
    
    # ossm-kiali:
    #    name: kiali-operator
    #    channel: stable
    
    # ossm:
    #    name: servicemesh-operator
    #    channel: stable
      
  projects:
    - hub
    - hello-world
    - postgresql

  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA
      
    aap-instance:
      name: ansible-automation-platform
      namespace: aap
      project: hub
      kustomize: true
      path: common/ansible-automation-platform/overlays/default

    rhacs:
      name: rhacs-operator
      namespace: rhacs-operator
      project: hub
      kustomize: true
      path: common/acs/overlays/default

    ossm-elasticsearch:
      name: elasticseach-operator
      namespace: openshift-operators-redhat
      project: hub
      kustomize: true
      path: common/elasticsearch/overlays/stable

    ossm-jaeger:
      name: jaeger-operator
      namespace: openshift-distributed-tracing
      project: hub
      kustomize: true
      path: common/jaeger/overlays/stable

    ossm-kiali:
      name: kiali-operator
      namespace: openshift-operators
      project: hub
      kustomize: true
      path: common/kiali/overlays/stable

    ossm:
      name: ossm-operator
      namespace: istio-system
      project: hub
      kustomize: true
      path: common/openshift-servicemesh/overlays/default

    rhbk:
      name: rhbk-sso
      namespace: rhbk-sso
      project: hub
      kustomize: true
      path: common/redhat-keycloak/overlays/stable-v22
    
    external-secrets-operator:
      name: external-secrets-operator
      namespace: external-secrets-operator
      project: hub
      path: common/external-secrets-operator

    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/all/hello-world

    postgresql:
      name: postgresql
      namespace: postgresql
      project: postgresql
      path: charts/all/postgresql

  imperative:
    jobs:
    - name: hello-world
      # ansible playbook to be run
      playbook: common/ansible/playbooks/hello-world/hello-world.yaml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false

      # Before enabling cluster provisioning, ensure AWS and/or Azure
      #   credentials and OCP pull secrets are defined in Vault.
      #   See values-secret.yaml.template
      #
      #clusterPools:
      #  exampleAWSPool:
      #    name: aws-ap
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      aws:
      #        region: ap-southeast-2
      #    clusters:
      #    - One
      #
      #  exampleAzurePool:
      #    name: azure-us
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      azure:
      #        baseDomainResourceGroupName: dojo-dns-zones
      #        region: eastus
      #    clusters:
      #    - Two
      #    - Three

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
