apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
  labels:
    app.kubernetes.io/instance: hello-world
data:
  "index.html": |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>Validate Pattern Demo</title>
        <style>
            body {
                background-color: orange;
                text-align: center;
                margin: 0;
                padding: 0;
            }
    
            .main-content {
                padding: 50px;
            }
    
            .thinking-gif {
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <div class="main-content">
            <h1 style="color: black;">CSA Validated Patterns Demo</h1>
            <h4 style="color: black;">Hub Cluster Domain : '{{ .Values.global.hubClusterDomain }}'</h4>
            <div class="thinking-gif">
                <iframe src="https://giphy.com/embed/YLsNriHj84dupx9XvQ"> width="391" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="#">@Luminus</a></p>
            </div>
        </div>
    </body>
    </html>
    



