apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhbk-sso-prod
  namespace: rhbk-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3
  ingress:
      className: openshift-default
  db:
    vendor: postgres
    host: postgres-db.postgresql.svc.cluster.local
    usernameSecret:
      name: rhbk-secret-from-akv
      key: psqluser
    passwordSecret:
      name: rhbk-secret-from-akv
      key: psqlpw
  http:
    tlsSecret: keycloak-cert-secret
    # httpEnabled: true
  hostname:
    hostname: keycloak.apps.dd-aro.eastus.aroapp.io
    # adminurl: https://keycloak.apps.dd-aro.eastus.aroapp.io
    # strict: false
    # strictBackchannel: false
