# apiVersion: v1
# data:
#   password: cG9zdGdyZXNxbAo=
#   username: cG9zdGdyZXNxbAo=
# kind: Secret
# metadata:
#   name: postgres-db-secret
#   namespace: rhbk-keycloak
# ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret-from-akv
  namespace: rhbk-keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv-cluster-secret
  target:
    name: rhbk-secret-from-akv
  data:
  - secretKey: psqluser
    remoteRef:
      key: secret/psqluname
  - secretKey: psqlpw
    remoteRef:
      key: secret/psqlpassword