apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret-from-akv
  namespace: rhbk-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv-cluster-secret-read
  target:
    name: rhbk-secret-from-akv
  data:
  - secretKey: psqluser
    remoteRef:
      key: secret/psqluname
  - secretKey: psqlpw
    remoteRef:
      key: secret/psqlpassword