apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls-cert-test
  namespace: rhbk-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv-cluster-secret
  target:
    name: rhbk-tls-cert
  data:
  - secretKey: tlscert
    remoteRef:
      key: cert/keycloakcert