---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hub-gitops-git-cm.yaml
  # - hub-gitops-server-route.yaml
  - openshift-gitops-git-cm.yaml
  # - openshift-gitops-server-route.yaml