---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - 01-rhacs-central.yaml
  - 02-rhacs-secured-cluster.yaml
  - 03-rhacs-create-cluster-init-bundle-job.yaml
  - 04-rhacs-create-cluster-init-bundle-sa.yaml
