---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: 01-instance-name-change.yaml
    target:
       version: v1beta1
       kind: AutomationController
       name: controller
       namespace: ansible-automation-platform
  
  - patch: |-
      - op: replace
        path: /spec/tls/termination
        value: reencrypt
    target:
      kind: Route
      name: ngc-aap-controller
