
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-root-cert
  namespace: rhbk-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  isCA: true
  commonName: Demo Cluster Certificate Authority - Self Signed
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - Keycloak Lab
    organizationalUnits:
      - NGC Demo
  issuerRef:
    name: cert-manager-ca-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
