
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - Red Hat Demo Lab
    organizationalUnits:
      - NGC Demo
  issuerRef:
    name: cert-manager-ca-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
