# Default values for hardedning.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enable_autoscaler: true

max_node_count: 9

min_aggregate_cpu: 48
max_aggregate_cpu: 72

min_aggregate_memory: 384
max_aggregate_memory: 576

min_replica_per_region: 1
max_replica_per_region: 2

name:
   - name: dd-aro-bqhs7-worker-eastus1
   - name: dd-aro-bqhs7-worker-eastus2
   - name: dd-aro-bqhs7-worker-eastus3


