apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-mirror-by-digest-registries
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,{{- range Values.image_mirrors }} 
                                                           {{ printf "[[registry]]
                                                             prefix = ""
                                                             location =%s" ".source"
                                                             "mirror-by-digest-only = false
                                                           
                                                           [[registry.mirror]]
                                                           location =%s" ".mirror" }}
                                                       {{- end }}
        overwrite: true
        filesystem: root
        mode: 420
        path: /etc/containers/registries.conf.d/99-worker-mirror-by-digest-registries.conf