{{ if .Values.acs.enabled }}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"    
spec:
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: false
    listenOnCreates: false
    listenOnEvents: true
  scanner:
    scannerComponent: Disabled
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
  clusterName: {{ (split "." .Values.global.localClusterDomain)._1 }}
  centralEndpoint: "central-stackrox.{{ .Values.global.hubClusterDomain }}:443"
{{ end }}
