apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SI System and Information Integrity
    policy.open-cluster-management.io/controls: SI-5 Security Alerts Advisories and
      Directives
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: policy-advanced-managed-cluster-security
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-advanced-managed-cluster-security
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              admission-control-cert.pem: '{{hub fromSecret "policies" "admission-control-tls"
                "admission-control-cert.pem" hub}}'
              admission-control-key.pem: '{{hub fromSecret "policies" "admission-control-tls"
                "admission-control-key.pem" hub}}'
              ca.pem: '{{hub fromSecret "policies" "admission-control-tls" "ca.pem"
                hub}}'
            kind: Secret
            metadata:
              name: admission-control-tls
              namespace: stackrox
            type: Opaque
        remediationAction: enforce
        severity: medium
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-advanced-managed-cluster-security2
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              ca.pem: '{{hub fromSecret "policies" "collector-tls" "ca.pem" hub}}'
              collector-cert.pem: '{{hub fromSecret "policies" "collector-tls" "collector-cert.pem"
                hub}}'
              collector-key.pem: '{{hub fromSecret "policies" "collector-tls" "collector-key.pem"
                hub}}'
            kind: Secret
            metadata:
              name: collector-tls
              namespace: stackrox
            type: Opaque
        remediationAction: enforce
        severity: medium
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-advanced-managed-cluster-security3
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              acs-host: '{{hub fromSecret "policies" "sensor-tls" "acs-host" hub}}'
              ca.pem: '{{hub fromSecret "policies" "sensor-tls" "ca.pem" hub}}'
              sensor-cert.pem: '{{hub fromSecret "policies" "sensor-tls" "sensor-cert.pem"
                hub}}'
              sensor-key.pem: '{{hub fromSecret "policies" "sensor-tls" "sensor-key.pem"
                hub}}'
            kind: Secret
            metadata:
              name: sensor-tls
              namespace: stackrox
            type: Opaque
        remediationAction: enforce
        severity: medium
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-advanced-managed-cluster-security4
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: SecuredCluster
            metadata:
              name: stackrox-secured-cluster-services
              namespace: stackrox
            spec:
              admissionControl:
                listenOnCreates: false
                listenOnEvents: true
                listenOnUpdates: false
              auditLogs:
                collection: Auto
              centralEndpoint: |
                {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
              clusterName: |
                {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
              perNode:
                collector:
                  collection: EBPF
                  imageFlavor: Regular
                taintToleration: TolerateTaints
        remediationAction: enforce
        severity: medium
  remediationAction: enforce