apiVersion: v1
kind: Secret
metadata:
  name: akv-sp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  ClientID: NTJiNGYxYTQtOWNhYi00N2U1LWI0MjEtYTg3ODNkZDIzODA3Cg==  #service-principal-ID
  ClientSecret: dTExOFF+eXUwb1FCMmVfV2hReER4MnhXb19zS1VIUzEzMmhrX2FldQo= #service-principal-secret