apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: 469f13ac-a9f4-417a-bc92-0eceaed61eca
    azure.workload.identity/tenant-id: 64dc69e4-d083-49fc-9569-ebece1dd1408

