# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   # this service account was created by azwi
#   name: workload-identity-sa
#   namespace: ekho-external-secrets    
#   annotations:
#       argocd.argoproj.io/sync-wave: "2"
#   annotations:
#     azure.workload.identity/client-id: 469f13ac-a9f4-417a-bc92-0eceaed61eca
#     azure.workload.identity/tenant-id: 64dc69e4-d083-49fc-9569-ebece1dd1408
# ---

---
apiVersion: v1
kind: Secret
metadata:
  name: akv-sp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  ClientID: YmNiNWY1NTItZmZkNS00ODM1LThhNWUtMDM3MTU0ZTEyYmYwCg==  #service-principal-ID
  ClientSecret: Zk9iOFF+X1BkY3MtVGIwdlNMa2N1WWxFQ2RiMG5ibEVXcU1qeGJiOQo= #service-principal-secret