apiVersion: v1
kind: Secret
metadata:
  name: akv-sp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  ClientID: YmNiNWY1NTItZmZkNS00ODM1LThhNWUtMDM3MTU0ZTEyYmYwCg==  #service-principal-ID
  ClientSecret: Zk9iOFF+X1BkY3MtVGIwdlNMa2N1WWxFQ2RiMG5ibEVXcU1qeGJiOQo= #service-principal-secret