---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akv-sp-secret-store
  namespace: ekho-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    azurekv:
      tenantId: 64dc69e4-d083-49fc-9569-ebece1dd1408
      vaultUrl: "https://dd-aro-cluster-akv-demo.vault.azure.net/"
      authSecretRef:
        clientId:
          name: akv-sp
          key: ClientID
        clientSecret:
          name: akv-sp
          key: ClientSecret

