---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - akv-integration-sa.yaml
  - akv-secretstore-sp.yaml
  - akv-externalsecret-read.yaml
  - akv-clustersecretstore.yaml
