apiVersion: v1
data:
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tKUbXNUd1lDTnh6ndlF3VUE23S0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUlnakNDQm1xZ0FUkzbWQ5SmlzUGRxOFhMUFRLc0EUtLS0tLQo=
kind: Secret
metadata:
  name: keycloak-tls-cert
  namespace: rhbk-sso