{{- if $.Values.acs.integrations }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: get-stackrox-api-token
  namespace: stackrox
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          ACSTOKEN=$(curl -sk -u "admin:$(oc get secret central-htpasswd -oyaml | grep "password" | awk '{print $2}' | base64 -d)" "https://central-stackrox.{{ .Values.global.hubClusterDomain }}/v1/apitokens/generate" -d '{"name":"name for the token here", "role": "Admin"}' | awk -F'"' '/token/{print $4}')
          oc create secret -n stackrox generic acs-api-token --from-literal=token=$ACSTOKEN
        name: stackrox-api-token
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 300
      restartPolicy: Never
      serviceAccountName: create-cluster-init
      terminationGracePeriodSeconds: 60
{{- end }}
