---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
  - ../../base
  - 01-rhacs-stackrox-image-integration-update-job-sa.yaml
  - 02-rhacs-stackrox-image-integration-update-job.yaml
  - 03-rhacs-stackrox-image-puller-sa.yaml
